// website/src/components/home/hero/hero.tsx
// imports
import { component$ } from "@builder.io/qwik";
import { Tag as TagList } from "@prisma/client";

// components
import Tag from "@/components/ui/tag/tag";
import Endline from "@/components/ui/endline/endline";
import GradientText from "@/components/ui/gradient/text";
import SearchBar from "@/components/home/hero/search/bar";

// home page quick search, hero
export default component$(() => {
  // fetching tags
  const JSONTagsList = JSON.parse(JSON.stringify(TagList));
  const Tags = Object.keys(TagList).map((key) => {
    return JSONTagsList[key].toLowerCase();
  });
  return (
    <section class="px-5 py-14">
      <div class="mb-9 flex flex-col mx-auto max-w-3xl justify-between">
        <h1 class="text-left font-semibold md:text-7xl text-5xl">
          Rev the <GradientText text="Revolt" /> bots...
        </h1>{" "}
        <SearchBar />
        <div class="mt-5 gap-x-4 overflow-x-scroll flex flex-scroll">
          {Tags.map((tag) => (
            <Tag label={tag} key={tag} />
          ))}
        </div>
      </div>
      <Endline />
    </section>
  );
});

// website/src/lib/components/Hero/index.svelte
<script>
	// imports

	// components
	import Tag from '$lib/components/UI/Tag.svelte';
	import Endline from '$lib/components/UI/Endline.svelte';
	import GradientText from '$lib/components/Gradient/Text.svelte';
	import SearchBar from '$lib/components/Hero/Searchbar.svelte';

	// tags list
	const Tags = ["Test"]
</script>

<section class="px-5 py-14">
	<div class="mb-9 flex flex-col mx-auto max-w-3xl justify-between">
		<h1 class="text-left font-semibold md:text-7xl text-5xl">
			Rev the <GradientText text="Revolt" /> bots...
		</h1>
		<SearchBar />
		<div class="mt-5 gap-x-4 overflow-x-scroll flex flex-scroll">
			{#each Tags as tag}
				<Tag label={tag} />
			{/each}
		</div>
	</div>
	<Endline />
</section>
